module.exports.shorten = {
  Biologia: 'BIO',
  'Educação Física': 'EDF',
  'Ensino Religioso': 'ENR',
  Filosofia: 'FIL',
  História: 'HIS',
  Inglês: 'ING',
  'Língua Portuguesa': 'LP',
  Matemática: 'MAT',
  'Projeto Interdisciplinar I': 'PD1',
  Química: 'QUI',
  Arte: 'ART',
  'Ensino Religioso II': 'ENR2',
  Física: 'FIS',
  Geografia: 'GEO',
  Espanhol: 'ESP',
  'Projeto Interdisciplinar II': 'PD2',
  'Projeto Interdisciplinar III': 'PD3',
  'Projeto Interdisciplinar IV': 'PD4',
  Sociologia: 'SOC',
};

module.exports.lengthen = {
  BIO: 'Biologia',
  EDF: 'Educação Física',
  ENR: 'Ensino Religioso',
  FIL: 'Filosofia',
  HIS: 'História',
  ING: 'Inglês',
  LP: 'Língua Portuguesa',
  MAT: 'Matemática',
  PD1: 'Projeto Interdisciplinar I',
  QUI: 'Química',
  ART: 'Arte',
  ENR2: 'Ensino Religioso II',
  FIS: 'Física',
  GEO: 'Geografia',
  ESP: 'Espanhol',
  PD2: 'Projeto Interdisciplinar II',
  PD3: 'Projeto Interdisciplinar III',
  PD4: 'Projeto Interdisciplinar IV',
  SOC: 'Sociologia',
};
