module.exports.shorten = {
  Biologia: 'bio',
  'Educação Física': 'edf',
  'Ensino Religioso': 'enr',
  Filosofia: 'fil',
  História: 'his',
  Inglês: 'ing',
  'Língua Portuguesa': 'lp',
  Matemática: 'mat',
  'Projeto Interdisciplinar I': 'pd1',
  Química: 'qui',
  Arte: 'art',
  'Ensino Religioso II': 'enr2',
  Física: 'fis',
  Geografia: 'geo',
  Espanhol: 'esp',
  'Projeto Interdisciplinar II': 'pd2',
  'Projeto Interdisciplinar III': 'pd3',
  'Projeto Interdisciplinar IV': 'pd4',
  Sociologia: 'soc',
};

module.exports.lengthen = {
  bio: 'Biologia',
  edf: 'Educação Física',
  enr: 'Ensino Religioso',
  fil: 'Filosofia',
  his: 'História',
  ing: 'Inglês',
  lp: 'Língua Portuguesa',
  mat: 'Matemática',
  pd1: 'Projeto Interdisciplinar I',
  qui: 'Química',
  art: 'Arte',
  enr2: 'Ensino Religioso II',
  fis: 'Física',
  geo: 'Geografia',
  esp: 'Espanhol',
  pd2: 'Projeto Interdisciplinar II',
  pd3: 'Projeto Interdisciplinar III',
  pd4: 'Projeto Interdisciplinar IV',
  soc: 'Sociologia',
};
